In [2]:
import sys
#sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import numpy as np
import cv2
import glob

In [4]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((3*5,3), np.float32)
objp[:,:2] = np.mgrid[0:5,0:3].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('/home/johan/Desktop/Jackal/Images_Calibration/*.png')

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  # Encuentra las esquinas del tablero de ajedrez
    ret, corners = cv2.findChessboardCorners(gray, (5,3),None)
    
  # Si se encuentran, añada puntos de objeto, puntos de imagen (después de refinarlos)
    if ret == True:
        #print('l')
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)
# Dibuja y muestra las esquinas
    #img = cv2.drawChessboardCorners(img, (7,6), corners2,ret)
    #cv2.imshow('img',img)
    #cv2.waitKey(500)
    #print(images)
#cv2.destroyAllWindows()
print('Ready!')

Ready!


In [5]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

In [6]:
print('matriz de cámara: ', mtx)

matriz de cámara:  [[738.21686205   0.         628.50641818]
 [  0.         739.34943414 343.58290083]
 [  0.           0.           1.        ]]


In [7]:
##3.1 cm medida real del cuadro, se multiplica por 0.31
mtx_or = mtx*0.31
print('mtx_or:\n',mtx_or)

mtx_or:
 [[228.84722723   0.         194.83698964]
 [  0.         229.19832458 106.51069926]
 [  0.           0.           0.31      ]]
